### PR TITLE
kiali SA to be given read-only perms unless using anonymous strategy …

### PR DESCRIPTION
**Pull request by jmazzitelli**
…with view_only_mode off

fixes: https://github.com/kiali/kiali/issues/5611

### CODE REVIEW

**Comment by jmazzitelli** [comment]
fyi: these molecule tests pass with these changes: `config-values-test`, `null-cr-values-test`, `only-view-only-mode-test`, `roles-test`

**Comment by jmazzitelli** [comment]
failing molecule tests: `config-values-test`, `header-auth-test`, `openid-test` - I'll figure out if those failures are related and fix as appropriate.

**Comment by jmazzitelli** [comment]
molecule tests all pass. requires that you pick up the hack script change for the tests to pass: https://github.com/kiali/kiali/pull/5641

**Review by leandroberetta — APPROVED** [review]
LGTM.

**Pull request merged**
