### PR TITLE
[molecule] move from community.kubernetes to kubernetes.core.k8s ansible collection

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4119

### CODE REVIEW

**Comment by jmazzitelli** [comment]
If we want to run molecule tests for v1.36 builds, we should backport this to that branch

**Comment by jmazzitelli** [comment]
all molecule tests pass on minikube. will try on openshift next

**Comment by jmazzitelli** [comment]
passes on openshift, too.

**Review by lucasponce — APPROVED** [review]

**Comment by jmazzitelli** [comment]
I re-ran molecule tests again on minikube and openshift and they all pass again. So I'm going to merge this.

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
