### PR TITLE
use k8s_cluster_info to get api version availability from the cluster

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/5857

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To test this, I just installed the latest minikube with dex, installed Istio, built and pushed the images via `make build build-ui cluster-push` then ran `./hack/run-molecule-tests.sh -dorp podman -ce $(which kubectl) -mp ci -ct minikube -udi true`. Everything passes:

```
=====================
=== TEST RESULTS: ===
=====================

              accessible-namespaces-test... success [9m 46s]
     affinity-tolerations-resources-test... success [4m 20s]
                      config-values-test... success [3m 26s]
                  default-namespace-test... success [2m 28s]
                            grafana-test... success [4m 20s]
                        header-auth-test... success [2m 38s]
                      instance-name-test... success [3m 34s]
                             jaeger-test... success [3m 18s]
                            metrics-test... success [4m 28s]
                     null-cr-values-test... success [2m 26s]
                only-view-only-mode-test... success [3m 24s]
                             openid-test... success [2m 22s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                 read-certs-secrets-test... success [2m 18s]
                              roles-test... success [6m 37s]
                    rolling-restart-test... success [3m 20s]
                              token-test... success [2m 43s]
```

**Comment by jmazzitelli** [comment]
a quick smoke test just to make sure nothing broke, you can just do a `make build build-ui cluster-push operator-create kiali-create` to ensure Kiali is installed and the operator works.

**Review by jshaughn — APPROVED** [review]
It seemed to work although my Kiali pod seemed a little sluggish to start, it was sitting at 0/1 container for about 30s.  Usually it starts immediately.

**Comment by jmazzitelli** [comment]
> It seemed to work although my Kiali pod seemed a little sluggish to start, it was sitting at 0/1 container for about 30s. Usually it starts immediately.

That is concerning. Let me hold off on merging this. I want to do some perf tested here. It is expected to be slower at start up, but not by that much. This is due to the introduction of the usage of:
```
- name: Get api version information from the cluster
  k8s_cluster_info:
  register: api_status
```

**Comment by jmazzitelli** [comment]
Running the operator profiler while on minikube, I can see this new task takes just under 1 second (I highlighted the profile line that shows this - search for `<<<<` and `>>>`).... so this should not be a concern, it is run only one time per reconciliation.

```
Tuesday 21 February 2023  21:41:54 +0000 (0:00:00.013)       0:00:25.618 ****** 
=============================================================================== 
default/kiali-deploy : Create resource [service] on [kubernetes] -------- 1.18s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 1.00s
default/kiali-deploy : Get information about the operator --------------- 0.96s
default/kiali-deploy : Determine if the operator can support accessible_namespaces=** - can_i create clusterroles --- 0.95s
default/kiali-deploy : Create resource [ingress] on [kubernetes] -------- 0.94s
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
default/kiali-deploy : Get api version information from the cluster ----- 0.91s
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
default/kiali-deploy : Create resource [deployment] on [kubernetes] ----- 0.86s
default/kiali-deploy : Create resource [role] on [kubernetes] ----------- 0.71s
default/kiali-deploy : Create resource [rolebinding-controlplane] on [kubernetes] --- 0.71s
default/kiali-deploy : Determine if the operator can support accessible_namespaces=** - can_i create clusterrolebindings --- 0.68s
default/kiali-deploy : Create resource [serviceaccount] on [kubernetes] --- 0.67s
default/kiali-deploy : Create resource [role-controlplane] on [kubernetes] --- 0.67s
default/kiali-deploy : Get information about any existing signing key secret if we need to know if it exists or not --- 0.67s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 0.66s
default/kiali-deploy : Remove HPA if disabled on Kubernetes ------------- 0.65s
default/kiali-deploy : Create resource [configmap] on [kubernetes] ------ 0.60s
default/kiali-deploy : Create resource [rolebinding] on [kubernetes] ---- 0.60s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 0.59s
default/kiali-deploy : Create kiali-signing-key secret to store a random signing key if a secret does not already exist and we need one --- 0.58s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 0.56s
default/kiali-deploy : Add label to kiali-signing-key secret to make it known this Kiali instance will be using it --- 0.53s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 0.53s
default/kiali-deploy : Update CR status progress field with any additional status fields --- 0.53s
default/kiali-deploy : Find all namespaces (this is limited to what the operator has permission to see) --- 0.36s
default/kiali-deploy : Determine if the currently installed role binding in the deployment namespace is view-only --- 0.35s
default/kiali-deploy : Find current configmap, if it exists ------------- 0.33s
default/kiali-deploy : Find current deployment, if it exists ------------ 0.31s
default/kiali-deploy : Get api group information from the cluster ------- 0.25s
default/kiali-deploy : Autodetect remote cluster secrets within the Kiali deployment namespace --- 0.24s
Run the version-specific deploy role ------------------------------------ 0.20s
default/kiali-deploy : Determine the Kubernetes version ----------------- 0.19s
default/kiali-deploy : Replace snake_case with camelCase in deployment.affinity.node --- 0.16s
default/kiali-deploy : Set default root namespace ----------------------- 0.15s
default/kiali-deploy : Replace snake_case with camelCase in deployment.affinity.pod --- 0.14s
default/kiali-deploy : Replace snake_case with camelCase in deployment.affinity.pod_anti --- 0.14s
default/kiali-deploy : Replace snake_case with camelCase in deployment.hpa.spec --- 0.13s
default/kiali-deploy : Replace snake_case with camelCase in external_services.prometheus.query_scope --- 0.11s
default/kiali-deploy : Replace snake_case with camelCase in deployment.configmap_annotations --- 0.11s
default/kiali-deploy : Create Kiali objects on Kubernetes --------------- 0.11s
default/kiali-deploy : Replace snake_case with camelCase in external_services.tracing.query_scope --- 0.10s
default/kiali-deploy : Replace snake_case with camelCase in deployment.security_context --- 0.10s
Override the supported images if found in the environment --------------- 0.10s
default/kiali-deploy : Replace snake_case with camelCase in external_services.prometheus.custom_headers --- 0.10s
default/kiali-deploy : Replace snake_case with camelCase in deployment.tolerations --- 0.10s
default/kiali-deploy : Replace snake_case with camelCase in external_services.custom_dashboards.prometheus.custom_headers --- 0.10s
default/kiali-deploy : Replace snake_case with camelCase in deployment.node_selector --- 0.09s
default/kiali-deploy : Replace snake_case with camelCase in deployment.service_annotations --- 0.09s
default/kiali-deploy : Replace snake_case with camelCase in deployment.pod_annotations --- 0.09s
default/kiali-deploy : Replace snake_case with camelCase in external_services.custom_dashboards.prometheus.query_scope --- 0.09s
default/kiali-deploy : Replace snake_case with camelCase in deployment.pod_labels --- 0.09s
default/kiali-deploy : Only allow ad-hoc kiali namespace when appropriate --- 0.09s
default/kiali-deploy : Print some debug information --------------------- 0.08s
Examine environment and determine if supported image for the requested version is overridden even if no default is known --- 0.07s
default/kiali-deploy : include_tasks ------------------------------------ 0.07s
default/kiali-deploy : set_fact ----------------------------------------- 0.07s
default/kiali-deploy : Create Kiali objects on OpenShift ---------------- 0.06s
default/kiali-deploy : api.namespaces.label_selector is deprecated but if api.namespaces.label_selector_include is not set then use the old setting --- 0.06s
default/kiali-deploy : Make sure instance_name follows the DNS label standard because it will be a Service name --- 0.06s
If upgrade is in progress then run the old version-specific remove role to purge old install --- 0.06s
Kiali CR status --------------------------------------------------------- 0.06s
default/kiali-deploy : include_tasks ------------------------------------ 0.06s
default/kiali-deploy : deployment.ingress_enabled is deprecated but if deployment.ingress.enabled is not set then use the old setting --- 0.06s
Kiali CR identification ------------------------------------------------- 0.06s
default/kiali-deploy : Set default istio namespace ---------------------- 0.06s
default/kiali-deploy : Replace snake_case with camelCase in deployment.additional_service_yaml --- 0.06s
default/kiali-deploy : include_tasks ------------------------------------ 0.06s
default/kiali-deploy : Replace snake_case with camelCase in deployment.resources --- 0.06s
Make sure a default supported image or an override image is known ------- 0.06s
default/kiali-deploy : include_tasks ------------------------------------ 0.06s
Playbook start time ----------------------------------------------------- 0.06s
default/kiali-deploy : include_tasks ------------------------------------ 0.06s
default/kiali-deploy : Set default deployment namespace to the same namespace where the CR lives --- 0.06s
default/kiali-deploy : Replace snake_case with camelCase in deployment.ingress.override_yaml --- 0.06s
Determine the version that is to be installed --------------------------- 0.06s
default/kiali-deploy : Create Ingress on Kubernetes if enabled ---------- 0.05s
default/kiali-deploy : include_tasks ------------------------------------ 0.05s
default/kiali-deploy : Set default web root based on cluster type ------- 0.04s
default/kiali-deploy : Listing of all accessible namespaces (includes regex matches) --- 0.04s
default/kiali-deploy : Abort if all namespace access is not allowed ----- 0.04s
default/kiali-deploy : Set default HPA api_version ---------------------- 0.03s
default/kiali-deploy : Abort if accessible namespaces contains namespaces not labeled --- 0.03s
default/kiali-deploy : Set default Tracing in_cluster_url for grpc consumption --- 0.03s
default/kiali-deploy : Validate signing key, if it is set in the CR ----- 0.03s
default/kiali-deploy : Set current deployment last-updated annotation timestamp for new deployments --- 0.03s
default/kiali-deploy : Create additional Kiali role bindings on all accessible namespaces on OpenShift --- 0.03s
default/kiali-deploy : Set default Grafana in_cluster_url --------------- 0.03s
default/kiali-deploy : Set default Istio service that provides version info (istiod service that was introduced in Istio 1.6) --- 0.03s
default/kiali-deploy : Point signing key to the generated secret -------- 0.03s
default/kiali-deploy : Provide some default resource limits ------------- 0.03s
default/kiali-deploy : Make sure label_selector_include is in the valid format name=value --- 0.03s
default/kiali-deploy : Set default identity cert_file based on cluster type (non-OpenShift clusters do not get a default identity) --- 0.03s
default/kiali-deploy : Set deployment.accessible_namespaces to a list of full namespace names --- 0.03s
default/kiali-deploy : Set default identity private_key_file based on cluster type (non-OpenShift clusters do not get a default identity) --- 0.03s
default/kiali-deploy : Determine version_label based on image_version --- 0.03s
default/kiali-deploy : Determine the version of the operator based on the version label --- 0.03s
default/kiali-deploy : Get labeled accessible namespaces ---------------- 0.03s
default/kiali-deploy : set_fact ----------------------------------------- 0.03s
default/kiali-deploy : Set default Prometheus URL ----------------------- 0.03s
default/kiali-deploy : fail --------------------------------------------- 0.03s
default/kiali-deploy : Create additional Kiali role bindings on all accessible namespaces on Kubernetes --- 0.03s
```

**Comment by jmazzitelli** [comment]
> It seemed to work although my Kiali pod seemed a little sluggish to start, it was sitting at 0/1 container for about 30s.

Actually, now that I read your comment carefully :) what you are saying has no bearing on this PR. The Kiali SERVER is unaffected by this PR... so it has no affect on Kiali server start up times. This only affects the operator reconciliation. But as soon as the Kiali server pod is created, however long it takes for that pod to start is completely unrelated to this PR.

**Pull request merged**
