### PR TITLE
[molecule] move to another ansible quay repo to run molecule

### PR DESCRIPTION
**Pull request by jmazzitelli**
See: https://github.com/ansible-community/molecule/discussions/3206
I have not tested this yet. But to test it, this should work:
`make -e FORCE_MOLECULE_BUILD=true molecule-build molecule-test`

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I added this "for review" in case someone else wants to test it now. DO NOT merge until this is tested. I have not tested yet. Working on other things, but I know this has to be fixed so I created this PR.

**Comment by jmazzitelli** [comment]
do not merge - this new quay repo image is not working like the old one

**Comment by jmazzitelli** [comment]
on minikube
```
              accessible-namespaces-test... success [4m 45s]
     affinity-tolerations-resources-test... success [4m 21s]
                      config-values-test... success [3m 19s]
                  default-namespace-test... success [2m 29s]
                            grafana-test... success [4m 22s]
                        header-auth-test... success [2m 23s]
                      instance-name-test... success [3m 36s]
                             jaeger-test... success [3m 20s]
                            metrics-test... success [4m 32s]
                     null-cr-values-test... success [2m 19s]
                only-view-only-mode-test... success [3m 25s]
                             openid-test... success [2m 31s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                 read-certs-secrets-test... success [2m 21s]
                              roles-test... success [6m 33s]
                    rolling-restart-test... success [3m 20s]
                              token-test... success [2m 45s]
```

I also tested the openshift specific tests on openshift (openshift-auth and the os-console-links). Those pass. So this is good.

**Review by jshaughn — APPROVED** [review]
our new home

**Pull request merged**
