### PR TITLE
Add apiGroups for telemetry and extensions

### PR DESCRIPTION
**Pull request by josunect**
This is required for https://github.com/kiali/kiali/issues/5274

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Don't forget to modify the OLM metadata. See: https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-role-permission-that-applies-to-resources-in-all-accessible-namespaces

- https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-upstream/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml#L482
- https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-community/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml#L482
- https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L536

**Comment by josunect** [comment]
> Don't forget to modify the OLM metadata. See: https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-role-permission-that-applies-to-resources-in-all-accessible-namespaces
> 
> You want to add that stuff to these 3 places:
> 
>     * https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-upstream/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml#L482
> 
>     * https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-community/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml#L482
> 
>     * https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L536

Thanks for pointing this out! I've looked in the wrong place and I though these steps were not applicable.

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Review by hhovsepy — APPROVED** [review]
Verified in a scope of main PR.

**Pull request merged**
