### PR TITLE
speed up the kiali remove playbook significantly by refactoring out all ansible loops

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/6032

### CODE REVIEW

**Comment by jmazzitelli** [comment]
If my testing shows this to be good, we might consider backporting this. It is that good.

**Comment by jmazzitelli** [comment]
Very quick timing test shows I reduced the remove processing from 25 seconds to 5 seconds.  The default molecule test reduced also by roughly 30 seconds.

**Comment by luksa** [comment]
Hey, do I understand correctly that the operator is actively deleting the resources owned by the Kiali resource? What don't you let the k8s garbage collector take care of it? Right now, I assume that both are trying to delete the same resources and are actually in a race. Are there no `409 Conflict` errors reported?

**Comment by jmazzitelli** [comment]
There are no conflicts because the resources are not deleted by the k8s GC. There are no owner references created by the kiali operator. I forget the reason why we had to do it that way  - I think it was part of the problems we were having with the watch-dependencies feature ... it's a long story. We might look into getting back to that in the future but for now, I'm pretty sure this change will make a big difference.

**Comment by luksa** [comment]
Are you sure? I see `ownerReferences` on all the resources:
```
$ k get deploy kiali -oyaml | yq .metadata.ownerReferences
- apiVersion: kiali.io/v1alpha1
  kind: Kiali
  name: kiali
  uid: fa1c0251-e335-4637-b185-a925c04fd354

$ k tree kiali kiali
NAMESPACE     NAME                                    READY  REASON  AGE  
istio-system  Kiali/kiali                             -              3m20s
istio-system  ├─ConfigMap/kiali                       -              2m49s
istio-system  ├─ConfigMap/kiali-cabundle              -              2m48s
istio-system  ├─Deployment/kiali                      -              2m44s
istio-system  │ ├─ReplicaSet/kiali-5bf7855b5          -              116s 
istio-system  │ │ └─Pod/kiali-5bf7855b5-hjp8r         True           115s 
istio-system  │ └─ReplicaSet/kiali-7fdb58d858         -              2m44s
istio-system  ├─Role/kiali                            -              2m48s
istio-system  ├─Role/kiali-controlplane               -              2m47s
istio-system  ├─RoleBinding/kiali                     -              2m46s
istio-system  ├─RoleBinding/kiali-controlplane        -              2m45s
istio-system  ├─Route/kiali                           -              2m42s
istio-system  ├─Secret/kiali-signing-key              -              2m57s
istio-system  ├─Service/kiali                         -              2m43s
istio-system  │ ├─EndpointSlice/kiali-vbwv7           -              2m43s
istio-system  │ └─Secret/kiali-cert-secret            -              2m43s
istio-system  └─ServiceAccount/kiali-service-account  -              2m50s
```

**Comment by jmazzitelli** [comment]
I dunno. I look up the yaml for created resources and I don't see any ownerReferences in the metadata (though I do see the operator-sdk annotations, but that's different) - e.g.:

```yaml
$ kubectl get roles -n istio-system kiali-controlplane -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    operator-sdk/primary-resource: kiali-operator/kiali
    operator-sdk/primary-resource-type: Kiali.kiali.io
  creationTimestamp: "2023-04-18T01:45:37Z"
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: dev
    version: dev
  name: kiali-controlplane
  namespace: istio-system
  resourceVersion: "757870"
  uid: 96b0ad2e-abba-4742-8f28-4b94d26f34c3
rules:
- apiGroups:
  - ""
  resourceNames:
  - cacerts
  - istio-ca-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

Compare that to the owner refs that are placed on the Pod showing the ReplicaSet ownership:

```
$ kubectl get pods -n istio-system kiali-6897bd6479-g4bqb -o jsonpath={.metadata.ownerReferences} | jq
[
  {
    "apiVersion": "apps/v1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "ReplicaSet",
    "name": "kiali-6897bd6479",
    "uid": "19bf2837-eaf7-4d30-acea-04422f119a5d"
  }
]
```

I'm running this on minikube:
```
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

**Comment by jmazzitelli** [comment]
This PR passes all molecule tests on openshift and minikube. cc @jshaughn

**Comment by nrfox** [comment]
> I dunno. I look up the yaml for created resources and I don't see any ownerReferences in the metadata (though I do see the operator-sdk annotations, but that's different) 

I think it depends on whether or not the resources of the CR are created in the same namespace as the CR. If `.spec.deployment.namespace == .metadata.namespace` then you get owner refs, otherwise you just get the label(s): `operator-sdk/primary-resource`. Looking at: https://sdk.operatorframework.io/docs/building-operators/ansible/reference/advanced_options/#owner-reference-injection resources with only the label aren't garbage collected. This behavior seems to just be a quirk of using the ansible operator sdk.

**Comment by jmazzitelli** [comment]
> I think it depends on whether or not the resources of the CR are created in the same namespace as the CR.

Ah.. yes. Good reminder. I forgot about that.

**Comment by jmazzitelli** [comment]
Putting this "in review" - we should at least get this into master, if not backported.

**Review by jshaughn — APPROVED** [review]
Code looks fine.  Speed test looks good!

```
master  time kubectl delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted

real	0m28.605s
user	0m0.075s
sys	0m0.027s

PR      time kubectl delete kiali kiali -n kiali-operator
kiali.kiali.io "kiali" deleted

real	0m4.927s
user	0m0.077s
sys	0m0.021s
```

Note that I originally tested using ` CLUSTER_TYPE=minikube make operator-delete`.  This test wasn't good because it drops the `kiali-operator` namespace, and that ended up taking a variable amount of time.

**Pull request merged**
