### PR TITLE
remove login and ldap auth strategies

### PR DESCRIPTION
**Pull request by jmazzitelli**
https://github.com/kiali/kiali/issues/3017

### CODE REVIEW

**Comment by jmazzitelli** [comment]
> It will be pending to update the OperatorHub metadata, because there are some references to the login strategy in the metadata.

Where are you seeing references to the strategy in the metadata? All metadata I know of already has this ripped out - e.g.:

OperatorHub.io community:
https://github.com/operator-framework/community-operators/blob/master/community-operators/kiali/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml

OperatorHub.io upstream: 
https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/kiali/1.22.0/kiali.v1.22.0.clusterserviceversion.yaml

RedHat OLM:
https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml

**Comment by israel-hdez** [comment]
> Where are you seeing references to the strategy in the metadata? All metadata I know of already has this ripped out - e.g.:

Hmm... I was looking at updated metadata files on this PR. But, as you say, I see the updated v1.22 metadata files in `master`.
OK. It's all right.

This can be merged.

**Comment by jmazzitelli** [comment]
> This can be merged.

we don't want to merge this until the other 3 are fully approved so we can merge them all together. So these need approval too:

https://github.com/kiali/kiali/pull/3044
https://github.com/kiali/kiali-ui/pull/1861
https://github.com/kiali/kiali.io/pull/270

**Comment by israel-hdez** [comment]
> we don't want to merge this until the other 3 are fully approved

We can merge :-)  This will just block the possibility to setup ldap or login auths. It won't cause any malfunction.
But you are the PR owner. So, as you wish ;)

**Pull request merged**
