### PR TITLE
remove ansible loops from deploy - should make it faster

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/6032

analogous to https://github.com/kiali/kiali-operator/pull/636 which sped up the remove playbook by removing ansible loops. This PR does the same only in the deploy playbook.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I'm hitting some molecule test failures, so this isn't ready yet, but preliminary results are interesting. All passing molecule tests are faster by about 30 seconds, with one (roles-test) faster over 2 minutes (test run without this PR took 6m 24s, with this PR it took 3m 41s).

**Comment by jmazzitelli** [comment]
molecule tests now pass on openshift. this should be good.

**Comment by jmazzitelli** [comment]
@jshaughn molecule tests pass on both minikube and openshift. this looks good.

**Review by jshaughn — APPROVED** [review]
Seems to work, and although I performed only a single test it saw a 25% improvement in the initial reconciliation:

```
master
progress:
  duration: "0:00:16"
  message: 6. Finished all resource creation
  specVersion: default

PR
progress:
  duration: "0:00:12"
  message: 6. Finished all resource creation
  specVersion: default

```

**Pull request merged**
