### PR TITLE
Changes necessary to move to Ansible Operator SDK 1.x

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of: https://github.com/kiali/kiali/issues/2983

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Travis fails because it is now being told to use operator-sdk to validate the manifests, but the manifests are still using the old bundle format. I suspect by the time we will merge this PR, those manifests will have been or need to be converted to the new bundle format - at that time, this will all work. Therefore I'm leaving `.travis.yml` as-is for now.

**Comment by jmazzitelli** [comment]
4.7 is now based on upstream 1.3 SDK - so that is what we should target:

```
$ docker run --entrypoint /usr/local/bin/ansible-operator --rm -i -t registry.redhat.io/openshift4/ose-ansible-operator:v4.7 version

ansible-operator version: "v1.3.0-ocp", commit: "648f8a1ce22e7e838ecdd395d2589a6bcbbfb13b", kubernetes version: "v1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

**Comment by jmazzitelli** [comment]
This is ready. We can merge it.

Though I would like to ask @israel-hdez if he can convert the travis stuff to the new GitHub Actions. It looks like travis isn't running anymore, I think it is because we moved to GitHub Actions.

**Comment by jmazzitelli** [comment]
Running into molecule test failures. Investigating.

**Comment by jmazzitelli** [comment]
looks good. I'll be running the full molecule test suite tonight.

**Comment by jmazzitelli** [comment]
All molecule tests pass.

This is ready. We can merge it.

**Review by jshaughn — APPROVED** [review]
LOK.  Do we even need that .travis.yml file anymore?

**Comment by jmazzitelli** [comment]
> Do we even need that .travis.yml file anymore?

I need to ask @israel-hdez how to convert it to the new github actions... for now, leave it so we know what has to run to do the tests.

**Comment by israel-hdez** [comment]
I thought I already moved to GHActions this repo... But I see I'm wrong.
I'll convert it later today.

**Comment by jmazzitelli** [comment]
see related PR: https://github.com/kiali/kiali-operator/pull/272

**Pull request merged**
