### PR TITLE
Add molecule tests for the Kiali API

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3291

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I seeded the list of tests to include calling most of the GET APIs that did not require any parameters other than a namespace name.

We can fill these in - making more complex calls and/or calling PUT, DELETE, PATCH APIs - to make more interesting tests. This will probably require the molecule test to install a simple demo app (maybe just a small 1 or 2 Deployment app in a demo namespace). I can work on making this demo app for testing next.

**Comment by jmazzitelli** [comment]
Some basic tests are in. This doesn't test every API nor does it test every permutation of the API it does test. However, it does test some basic API functionality so it at least confirms the server can respond appropriately/successfully to API calls. We can fill these tests out as we see fit going forward in the future.

**Comment by jmazzitelli** [comment]
I confirmed all tests, including this new api-test, pass on minikube and OpenShift. This is ready for merge.

**Review by jshaughn — APPROVED** [review]
Visually fine and tests are passing on mazz-basement.

**Pull request merged**
