### PR TITLE
Adjust molecule tests because of header auth refactor

### PR DESCRIPTION
**Pull request by israel-hdez**
Related back-end PR: kiali/kiali#4867

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Build with the server PR, I got this error in the molecule test:
```
TASK [Make a request that requires authentication (should now return 200)] *****
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "Internal Server Error\n", "content_length": "22", "content_type": "text/plain; charset=utf-8", "date": "Fri, 01 Apr 2022 18:03:51 GMT", "elapsed": 0, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "https://192.168.59.167/kiali/api/namespaces", "vary": "Accept-Encoding", "x_content_type_options": "nosniff"}
```

Server log had this:
```
        "2022-04-01T18:03:51Z WRN Could not read the session: error when restoring the session - failed to parse the session payload: json: Unmarshal(non-pointer authentication.headerSessionPayload)",
```

Confirmed this was using my local build:
```
        "2022-04-01T18:03:03Z INF Kiali: Console version: 1.49.0-local-097103db3171b1c27cc3409edac1151d8ad29e4f",
```

**Comment by israel-hdez** [comment]
@jmazzitelli Yup, here is the fix: https://github.com/kiali/kiali/pull/4867/commits/7883595d8ddbaf3db1673f2100350349c1aed2d1
It's now pushed.

**Comment by jmazzitelli** [comment]
Test passes. Because the last assertion in that molecule test wants to confirm it can see a namespace as the authenticated user, you have to use the run-molecule-tests.sh hack script to run this test because it sets up the user and its permissions (otherwise, using the normal make molecule-test will result in an error).

So I ran this and test passes:

Build and push:
```
make -e MINIKUBE_PROFILE=ci -e CLUSTER_TYPE=minikube -e MOLECULE_SCENARIO="header-auth-test" -e MOLECULE_USE_DEV_IMAGES="true" clean build build-ui test cluster-push
```

Run test:
```
hack/run-molecule-tests.sh --cluster-type minikube --client-exe $(which kubectl) -mp ci -dorp podman -at "header-auth-test" -udi true
```

**Review by jmazzitelli — APPROVED** [review]

**Comment by jmazzitelli** [comment]
@israel-hdez we good to merge this?

**Comment by israel-hdez** [comment]
With the changes that the original author asked, this shouldn't be needed anymore. I'll close this.
Molecules should still pass without this.

**Pull request closed without merging**
