### PR TITLE
Expose metrics properly

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: kiali/kiali#2763

you can use the hack script to see the metrics in a local prom using the hack script - see https://github.com/kiali/kiali/pull/2766

### CODE REVIEW

**Comment by jmazzitelli** [comment]
See: https://github.com/operator-framework/operator-sdk/blob/v0.17.0/pkg/metrics/metrics.go#L112

We need a label "name" on the operator deployment.

**Comment by jmazzitelli** [comment]
The golden copy manifests for our next versions will need to alter the Deployment yaml - needs to match the changes to the deploy/operator.yaml done here in this PR.

**Comment by jmazzitelli** [comment]
To test, run the molecule test thusly:

1. Build this PR and push to your cluster via `make cluster-push`
2. Execute: `MOLECULE_USE_DEV_IMAGES=true MOLECULE_SCENARIO=metrics-test make molecule-test`

Or you can simply build and run `make operator-create kiali-create` and look at Prometheus and check that you have the different sets of metrics - if you see these three metrics, then you know it is working:

* `kiali_api_processing_duration_seconds_count` (this comes from the Kiali server)
* `kiali_info` (this comes from port 8686/metrics of the operator)
* `workqueue_work_duration_seconds_count` (this comes from port 8383/metrics of the operator)

There are many more metrics, but those three come from the three different metric endpoints.

**Comment by FilipB** [comment]
kialiqeci

**Comment by rhqci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
