### PR TITLE
speed up the setting up of defaults in the operator

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/6132

### CODE REVIEW

**Comment by jmazzitelli** [comment]
just an experiment to see what this would do. Haven't done any examination of the performance data other than quick smoke testing -- seems this makes things faster but not as fast as I was expecting.

**Comment by jmazzitelli** [comment]
I did a quick test. I extracted only the code that is changing - first into [set-defaults-original.yml](https://github.com/kiali/kiali-operator/files/11909883/set-defaults-original.yml.txt)
and then the updated code that uses raw jinja: [set-defaults-jinja.yml](https://github.com/kiali/kiali-operator/files/11909889/set-defaults-jinja.yml.txt)

I then ran with `ansible.cfg` that enabled the profiler:
```
[defaults]
callbacks_enabled = profile_tasks
callback_whitelist = profile_tasks
```

The results:

The original code (`ansible-playbook set-defaults-original.yml`):
```
PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=0    skipped=19   rescued=0    ignored=0   

Thursday 29 June 2023  15:49:41 -0400 (0:00:00.042)       0:00:01.448 ********* 
```

The jinja code that does the same only with jinja expressions, not ansible tasks (`ansible-playbook set-defaults-jinja.yml`)
```
PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   

Thursday 29 June 2023  15:50:15 -0400 (0:00:00.040)       0:00:00.341 ********* 
```

So the good news is this PR speeds up the replaced code by a whopping 80% (from 1.5s to 0.3s).
The not-so-good news (not that it is bad) is that really, from a absolute time perspective, we only just shave off 1 second from the total processing time of the operator so it doesn't really do a whole lot.

That said, we DO get a speed improvement (albeit 1 second). So this could be merged if we want to eek out some more improvement.

**Comment by jshaughn** [comment]
up to you

**Comment by jmazzitelli** [comment]
I'm going to put this ready for review and merge when accepted.
It is faster (albeit in a minor way), the code is just as easy to maintain, and I did confirm it works -- all molecule tests pass.

```
=====================
=== TEST RESULTS: ===
=====================

              accessible-namespaces-test... success [8m 32s]
     affinity-tolerations-resources-test... success [3m 40s]
                cluster-wide-access-test... success [9m 9s]
                      config-values-test... success [2m 56s]
                  default-namespace-test... success [2m 2s]
                            grafana-test... success [3m 45s]
                        header-auth-test... success [1m 54s]
                      instance-name-test... success [2m 34s]
                             jaeger-test... success [2m 50s]
                            metrics-test... success [3m 59s]
                     null-cr-values-test... success [1m 50s]
                only-view-only-mode-test... success [2m 45s]
                             openid-test... success [1m 58s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                 read-certs-secrets-test... success [1m 51s]
                              roles-test... success [5m 51s]
                    rolling-restart-test... success [2m 46s]
                              token-test... success [2m 11s]
```

**Review by jshaughn — APPROVED** [review]
In Mazz we trust. LOK

**Pull request merged**
