### PR TITLE
Add "allowed_domains" configuration for OpenID

### PR DESCRIPTION
**Pull request by israel-hdez**
Supporting changes for community contribution https://github.com/kiali/kiali/pull/4296

Related kiali/kiali#4288.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]

**Comment by jshaughn** [comment]
@israel-hdez This seems stalled, what is the next step?

**Comment by israel-hdez** [comment]
@jshaughn  This is because of a community contribution.
I'll re-ask if the contributor has time to continue with this. If not, I'll simply close these PRs because I don't have how to try the code (which is specific to Google Auth).

**Comment by jshaughn** [comment]
@israel-hdez Ah, OK, I was confused because it had been approved by Mazz.  Take whatever action seems appropriate.

**Comment by israel-hdez** [comment]
Closing, because the community user cannot finish this work for now.

**Pull request closed without merging**
