### PR TITLE
[operator] bump operator base image to 4.17 / 1.35.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/7856

### CODE REVIEW

**Comment by jmazzitelli** [comment]
molecule tests all pass. I also looked for any deprecation notices in the output (sometimes ansible deprecates things - when they do they make loud log messages telling you about the usage of deprecated features) - there are no such notices.

So I think this is ready.

**Comment by jmazzitelli** [comment]
I'm seeing this now... not sure if something changed in the way the profiler works in new Ansible:

`[WARNING]: Skipping callback plugin 'profile_tasks', unable to load `

**Comment by jmazzitelli** [comment]
Turns out the new Ansible 2.15 (which is under the covers in the new base image) no longer has profile_tasks plugin in core. You have to install the ansible.posix collection to get it. So that is now installed in the build.

```
$ podman run  -it --rm --entrypoint '' quay.io/kiali/kiali-operator:dev ansible-galaxy collection list

# /opt/ansible/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.6.2  
community.general 7.5.0  
kubernetes.core   4.0.0  
operator_sdk.util 0.5.0
```

**Review by jshaughn — APPROVED** [review]
No problems, clean build, operator-create, edited CR, reconciled, operator-delete.

**Pull request merged**
