### PR TITLE
[molecule] support for existing operator that does not allow for ad-hoc kiali namespace

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3852

### CODE REVIEW

**Comment by jmazzitelli** [comment]
How I am testing:

1. Currently, no released operator has the allow-ad-hoc setting, so I need to build and push a dev image - here I build and push to my minikube:
```
make -e CLUSTER_TYPE=minikube cluster-push-operator
```
2. Now I install that dev operator to the "openshift-operators" namespace in my minikube via helm ("openshift-operators" to mimic where OLM puts the operator) - make sure to turn off the `allowAdHocKialiNamespace` feature since that will be how OLM operators will behave in the future:
```
kubectl create namespace openshift-operators && \
helm install \
  --namespace openshift-operators \
  --set allowAdHocKialiNamespace=false \
  --set image.repo=192.168.99.100:5000/kiali/kiali-operator \
  --set image.tag=dev \
  --repo https://kiali.org/helm-charts \
  kiali-operator \
  kiali-operator
```
3. Run a molecule test, telling it you already installed an operator in `openshift-operators` namespace (`MOLECULE_OPERATOR_INSTALLER=skip`)
```
make -e MOLECULE_OPERATOR_INSTALLER="skip" \
  -e CLUSTER_TYPE=minikube \
  -e MOLECULE_SCENARIO="default" \
  molecule-test
```

**Comment by jmazzitelli** [comment]
all tests pass using the mechanism described above but using run-molecule.sh to run all the tests on minikube:

```
./hack/run-molecule-tests.sh -oi skip -ct minikube 
```

Results:
```
              accessible-namespaces-test... success [7m 1s]
     affinity-tolerations-resources-test... success [6m 7s]
                                api-test... success [4m 35s]
                      config-values-test... success [8m 12s]
                  default-namespace-test... success [2m 46s]
                        header-auth-test... success [2m 51s]
                            metrics-test... success [6m 3s]
                     null-cr-values-test... success [2m 29s]
                only-view-only-mode-test... success [4m 8s]
                             openid-test... success [2m 13s]
                     openshift-auth-test... skipped
                   os-console-links-test... skipped
                              roles-test... success [9m 47s]
                    rolling-restart-test... success [3m 53s]
                              token-test... success [2m 34s]
```

**Comment by jmazzitelli** [comment]
Since testing with non-default CR spec.version requires helm chart in master (i.e. it isn't released yet) we need to build and use a local helm chart in order to do this testing. Here's the steps I did:

1. I used minikube so I installed minikube + istio using the hack scripts:
```
hack/k8s-minikube.sh start --dex-enabled true -kv 1.18.0
hack/k8s-minikube.sh istio
```
2. Build and push a local dev build of the operator
```
make -e CLUSTER_TYPE=minikube cluster-push-operator
```
3. Build a local helm chart and install the operator using it (this ensures the operator is given all roles needed to test all spec.versions)
```
cd <helm charts local git repo>
kubectl create namespace openshift-operators
make clean build-helm-charts
./_output/helm-install/helm template \
  --namespace openshift-operators \
  kiali-operator \
  --set allowAdHocKialiNamespace=false \
  --set image.repo=192.168.99.100:5000/kiali/kiali-operator \
  --set image.tag=dev \
  ./_output/charts/kiali-operator-*-SNAPSHOT.tgz \
  --include-crds | kubectl apply -f -
```
4. Run the tests with the v1.24 playbook
```
./hack/run-molecule-tests.sh -ct minikube -oi skip -sv v1.24
```

It is possible that some tests might fail - this is because we are running the molecule tests from the master branch, and they might be testing features not present in the v1.24 codebase. Now that the molecule tests can support testing existing operators with different spec.versions, in the future it will be possible to change to the spec.version branch and run the molecule tests from that branch.

**Comment by jmazzitelli** [comment]
This is ready for review and merge.

**Comment by jmazzitelli** [comment]
@mattmahoneyrh @pbajjuri20 I don't know if you'll be able to actually run this (requires some fiddling with your dev environment)... but you can review and approve and I'll get this merged for our release this week. This will be needed for you do run the molecule tests with OLM-installed operators.

**Review by mattmahoneyrh — APPROVED** [review]

**Pull request merged**
