### PR TITLE
be able to define the node port if the service type is "NodePort"

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/7093

### CODE REVIEW

**Comment by jmazzitelli** [comment]
To test.

1. Start any k8s cluster; I'll assume minikube.
2. Build, push, and install everything with NodePort service type:
```
make -e CLUSTER_TYPE=minikube -e SERVICE_TYPE=NodePort build build-ui cluster-push operator-create kiali-create
```
3. Check that you have a dynamically assigned nodePort in the service:
```
$ kubectl get svc -n istio-system kiali -ojsonpath='{.spec.ports[?(@.name=="http")].nodePort}{"\n"}'
32301
```
4. Now edit the Kiali CR (`kubectl edit kiali kiali -n kiali-operator`) and set `spec.server.node_port` to `32444` .
5. Wait for the Kiali CR to fully reconcile. Then check the node port in the same way you did in step 3. The node port should now be `32444`.

**Comment by jmazzitelli** [comment]
molecule test now checks that the node port can be set.

```
make \
   -e MOLECULE_SCENARIO="config-values-test" \
   -e CLUSTER_TYPE=minikube \
   -e MOLECULE_USE_DEV_IMAGES="true" \
   build build-ui cluster-push molecule-test
```

**Comment by jmazzitelli** [comment]
do not merge until the server helm chart PR is ready to go: https://github.com/kiali/helm-charts/pull/248

**Review by jshaughn — APPROVED** [review]
Thanks for doing this to complement the community addition to Helm Chart.

**Pull request merged**
