### PR TITLE
session timeout test

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4164

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This fails currently. I do not know why.

```
    TASK [Session should have timed out - request should fail] ***********************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "connection": "close",
    "content": "[{\"name\":\"istio-system\",\"labels\":{\"topology.istio.io/network\":\"network-default\"}}]",
    "content_length": "82",
    "content_type": "application/json",
    "cookies": {},
    "cookies_string": "",
    "date": "Mon, 12 Jul 2021 16:25:55 GMT",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "creates": null,
            "dest": null,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Cookie": "kiali-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SWpsaU1qZ3labUl5TjJJd04yUXpNamcxWlRoa1pUSm1PV1JqTmpVNFlqVTNZVFpqTnpJd1pUY2lmUS5leUpwYzNNaU9pSm9kSFJ3Y3pvdkx6RTVNaTB4TmpndE9Ua3RNVE0xTG01cGNDNXBiem96TWpBd01DSXNJbk4xWWlJNklrTnBVWGRQUjBVMFRtcG5NRmxwTVd0WmFtYzBURlJTYVU1NlRYUlBWRUpvVDFNd2Vsa3lVWGhPYWxsNFdtcFZNRTVxV1ZOQ1YzaDJXVEpHY3lJc0ltRjFaQ0k2SW10cFlXeHBMV0Z3Y0NJc0ltVjRjQ0k2TVRZeU5qRTVNelV6TkN3aWFXRjBJam94TmpJMk1UQTNNVE0wTENKdWIyNWpaU0k2SWpNNFpERXlNbVZoTnpRM1pXTmtOR0UyTVRNNFptVm1aV0V3Wm1ZeE1tWXpZekJtWW1Jd1lUa3pOR1kwT0RZMFltTXhNREF3WWpoaElpd2lZWFJmYUdGemFDSTZJbUZsVG5SMFQyUTRXVXBWT1dkWlZYZDZSWGRPVEZFaUxDSmxiV0ZwYkNJNkltRmtiV2x1UUdWNFlXMXdiR1V1WTI5dElpd2laVzFoYVd4ZmRtVnlhV1pwWldRaU9uUnlkV1VzSW01aGJXVWlPaUpoWkcxcGJpSjkuS3czaWZUM3ptNzZqdlJzTko5NUFxZmpFSWxLbXRmYURERmVsSXpJS1JGdm0wUGpxWW9mTTZ0Z0N6dnlFcUZmVWZfb250VnhoNmpBdkk1Ny1SM0t6OFhHcVhIYzZoRWV4dURSbjk4VXpfTkM2ZlBCSHQ4dFFqaEU4S19ONEFGUUp1bHEyTkZSSmlpdmhZd3hoZmVaZlFtRmpWV1Uzc0plOXFFY3M4NW9JUlhUTmx1MXRlSTlmS0ZxampYNWhCTFhLUHFmcXY5N2JxTFc0U2hpaDVKc0JuamNvYVBCQndUMFlIM0pZN1Y4RGNuYjRKamdacmtIRFc1UGFvODRGWTFnUUlsVzRrbkVoTGNmR3hlUlJQWW1CY3hoWVhlaFpTaGpUdi03NlYtS2dnUGx2d3EzaUxHWE1jd040MWN4S2RnRWpoa0RYNkRfVHJhSjFSV1dhOW9qSmJ3IiwiZXhwIjoxNjI2MTkzNTM0LCJpc3MiOiJraWFsaS1vcGVuLWlkIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20ifQ.3SWt93GHN9C8VMySDCrq4U5V0KSRqSWx3KDeYG0wVg0"
            },
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "remote_src": false,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "400"
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": false,
            "url": "https://192.168.99.135/kiali/api/namespaces",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "json": [
        {
            "labels": {
                "topology.istio.io/network": "network-default"
            },
            "name": "istio-system"
        }
    ],
    "msg": "Status code was 200 and not [400]: OK (82 bytes)",
    "redirected": false,
    "status": 200,
    "url": "https://192.168.99.135/kiali/api/namespaces",
    "vary": "Accept-Encoding"
}
```

**Comment by jmazzitelli** [comment]
To run the test:

1. Start minikube: `hack/k8s-minikube.sh start --dex-enabled true`
2. Run test (don't use `-dorp podman` if using docker): `hack/run-molecule-tests.sh --client-exe $(which kubectl) -dorp podman --cluster-type minikube -at openid-test`

**Comment by jmazzitelli** [comment]
@israel-hdez Can you look at this? This test is setting the expiration time to 15 seconds, waits for 20 seconds, and is still able to log in. The session isn't timing out. See [previous comment](https://github.com/kiali/kiali-operator/pull/354#issuecomment-878463980) for how you can run this (you don't need to build or push any dev images to minikube - let the test pull the latest images from quay - you just need this PR to get the change to the molecule test)

**Comment by israel-hdez** [comment]
Well this is testing openid auth.

I reckon that `expiration_seconds` config is misleading. That one controls session expiration for `token` auth strategy. For all others (i.e `openshift`, `openid`, `header`), session timeout is controlled on the 3dr party system.

For Dex, this is the Dex configuration that controls how long the session will last: https://github.com/dexidp/dex/blob/d4bd37156dd82be4deb4b2fbf54818c0d3383a11/examples/config-dev.yaml#L80.

There should be a ConfigMap named `dex` with that config YAML. Change it, restart Dex, and this test should pass.

**Comment by jmazzitelli** [comment]
> That one controls session expiration for `token` auth strategy.

We should make this more explicit in the docs here: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L827-L829

We need to say something like "This is applicable to token auth strategy only".

I will close this PR since the test framework doesn't know anything about Dex - it just assumes some openid provider was configured in the cluster it is running in.

**Comment by jshaughn** [comment]
+1, let's update the docs with the good info we have above. @israel-hdez please create a PR, no issue necessary.

**Pull request closed without merging**
