### PR TITLE
Adding istiod deployment name into the CR

### PR DESCRIPTION
**Pull request by xeviknal**
Adding a field into the `external_services.istio` section to allow users define the specific name of the istiod deployment.
Scenarios like: Istio canary upgrades and OSSM needs a different name.

This approach has been followed a previous work related to the config map:
```
external_services:
  istio:
    istiod_deployment_name: "istiod-1-9-1"
    config_map_name: "istio-1-9-1"
```

This PR needs https://github.com/kiali/kiali/pull/3796 to be merged first.

### CODE REVIEW

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
You need to set the default value in the `defaults/main.yml` file here: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/defaults/main.yml#L152

```
...
  istio_sidecar_annotation: "sidecar.istio.io/status"
  istiod_deployment_name: "istiod"   <---- ADD THIS
  url_service_version: ""
...

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Review by hhovsepy — APPROVED** [review]
Verified the installation.

**Comment by christian-posta** [comment]
what release will this be in?

**Comment by jmazzitelli** [comment]
> what release will this be in?

sprint ends this Friday - so Friday's release this should be there.

**Comment by jshaughn** [comment]
that would be 1.32.0

**Pull request merged**
