### PR TITLE
Add Enable flag on custom_dashboards

### PR DESCRIPTION
**Pull request by jotak**
Fixes https://github.com/kiali/kiali/issues/3269

Kiali PR: https://github.com/kiali/kiali/pull/3283

### CODE REVIEW

**Comment by jotak** [comment]
@jmazzitelli after this is merged do you want to go on with some optimization of the operator as you described here: https://github.com/kiali/kiali/issues/3269#issuecomment-700709692 ?

**Comment by jmazzitelli** [comment]
> after this is merged do you want to go on with some optimization of the operator as you described here: [kiali/kiali#3269 (comment)](https://github.com/kiali/kiali/issues/3269#issuecomment-700709692)

Yes. We will want another github issue for that.

**Comment by jmazzitelli** [comment]
@jotak do we want this backported to v1.24 or no?

**Comment by jotak** [comment]
> @jotak do we want this backported to v1.24 or no?

I would say no ...

**Review by jmazzitelli — APPROVED** [review]

**Pull request merged**
