### PR TITLE
Adding permissions for fetching proxy-status

### PR DESCRIPTION
**Pull request by xeviknal**
In order to fetch the proxy status, we need to use the sub-resource `proxy` from the pods.
Needs https://github.com/kiali/kiali/pull/3126

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
LGTM

@xeviknal I assume this is NOT going to be backported to v1.24. Correct? If so, you'll want to modify the same files in the roles/v1.24 directory ( (but that is only if you need to backport). But I will approve because I think this is not going to be backported.

**Comment by lucasponce** [comment]
>  I assume this is NOT going to be backported to v1.24. Correct

Right, this is for master only, no plans to backport it into the v1.24 branch.

**Review by lucasponce — APPROVED** [review]

**Comment by hhovsepy** [comment]
Seeing this error is kiali-operator pod's logs:
`[0;31mfatal: [localhost]: FAILED! => {"attempts": 6, "changed": false, "error": 403, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"roles.rbac.authorization.k8s.io \\\\\"kiali\\\\\" is forbidden: user \\\\\"system:serviceaccount:kiali-operator:kiali-operator\\\\\" (groups=[\\\\\"system:serviceaccounts\\\\\" \\\\\"system:serviceaccounts:kiali-operator\\\\\" \\\\\"system:authenticated\\\\\"]) is attempting to grant RBAC permissions not currently held:\\\\n{APIGroups:[\\\\\"\\\\\"], Resources:[\\\\\"pods/proxy\\\\\"], Verbs:[\\\\\"get\\\\\" \\\\\"list\\\\\" \\\\\"patch\\\\\" \\\\\"watch\\\\\"]}\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"kiali\",\"group\":\"rbac.authorization.k8s.io\",\"kind\":\"roles\"},\"code\":403}\\n'", "reason": "Forbidden", "status": 403}[0m`

**Comment by xeviknal** [comment]
I can confirm that I have been able to install the whole feature into an Openshift environment. I guess that there is a need to tweak something in the install process @hhovsepy

**Pull request merged**
