### PR TITLE
[v1.63] the 1.63.1 manifest - this is the first release for istio 1.17

### PR DESCRIPTION
**Pull request by jmazzitelli**
part of https://github.com/kiali/kiali/issues/5773

this is for the v1.63 branch for when we build 1.63.1. We need this also in the master branch

### CODE REVIEW

**Comment by leandroberetta** [comment]
@jmazzitelli isn't the pipeline creates this files? Or that is just for minor releases?.

**Comment by leandroberetta** [comment]
> @jmazzitelli isn't the pipeline creates this files? Or that is just for minor releases?.

I checked and only generates manifests for minor releases

**Review by jshaughn — COMMENTED** [review]
LOK

**Comment by jmazzitelli** [comment]
Yeah, @leandroberetta this needs to have the 1.63.1 metadata in the branch because when I produce the actual OLM PRs, I do it from the branch. so these need to be in there

**Pull request merged**
