### PR TITLE
Be able to disable ad hoc images.

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/3865

### CODE REVIEW

**Comment by jmazzitelli** [comment]
An admin can allow this by setting the env var on the operator deployment like this:

`kubectl -n ${OPERATOR_NAMESPACE} set env deployment/kiali-operator ALLOW_AD_HOC_KIALI_IMAGE=true`

**Comment by jmazzitelli** [comment]
Test this in a similar way as https://github.com/kiali/kiali-operator/pull/278
I just confirmed it works myself.

**Comment by jmazzitelli** [comment]
@israel-hdez please review - this addresses the image override stuff you mentioned recently.

**Review by israel-hdez — APPROVED** [review]
The new flag works OK for "default". I didn't try v1.24 nor v1.12 -- I trust you that these work.

**Pull request merged**
