### PR TITLE
support mounting custom secrets in the kiali pod

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4468

### CODE REVIEW

**Comment by jmazzitelli** [comment]
there is a molecule test to make sure the secret mounts are created correctly... I tested on minikube like this:

```
make -e MOLECULE_SCENARIO="config-values-test" \
     -e MOLECULE_USE_DEV_IMAGES="true" \
     -e CLUSTER_TYPE=minikube \
     cluster-push molecule-test
```

**Comment by jmazzitelli** [comment]
additional testing of the concepts this PR provides looks good: https://github.com/kiali/kiali/issues/4468#issuecomment-963748833

**Review by jshaughn — APPROVED** [review]
LOK.  Any kiali.io changes/additions needed?

**Comment by jmazzitelli** [comment]
> LOK. Any kiali.io changes/additions needed?

no. We have the docs in kiali_cr.yaml - edgar is in the process of moving those docs in kiali.io somewhere.

**Comment by jmazzitelli** [comment]
assigning to @mattmahoneyrh so he can determine if the community testing and molecule testing is good enough.

**Pull request merged**
