### PR TITLE
molecule test for the new dashboard annotations

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/kiali/kiali/issues/4160

Goes with issue https://github.com/kiali/kiali/issues/4145 and PR https://github.com/kiali/kiali/pull/4146 - only when that PR gets merged should we merge this PR since this new molecule test will only pass with that new code.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I'm running this with PR https://github.com/kiali/kiali/pull/4146 and I'm seeing errors. I think there might be a problem there.

**Comment by jmazzitelli** [comment]
Here's a way to test what this molecule test is doing - I documented this over in the github issue: https://github.com/kiali/kiali/pull/4146#issuecomment-876752008

**Comment by jmazzitelli** [comment]
`make -e CLUSTER_TYPE=minikube -e MOLECULE_SCENARIO="api-test" -e MOLECULE_USE_DEV_IMAGES=true molecule-test`

That will run the api-test which includes this new dashboard set of tests.

**Comment by jmazzitelli** [comment]
These tests (correctly) fail right now given the current state of the dashboard PRs - once those are fixed, these tests should pass.

**Comment by jmazzitelli** [comment]
This molecule test now passes with the new dashboard annotations PR. We can merge this when that gets merged also.

**Comment by jmazzitelli** [comment]
@lucasponce when you merge your [dashboard annotations PR](https://github.com/kiali/kiali/issues/4145), please approve and merge this one (this contains molecule tests that show your PR working).

**Comment by jmazzitelli** [comment]
We [need to](https://github.com/kiali/kiali/pull/4146#issuecomment-879093471) modify this test so the Namespace is created as a Project when run on OpenShift.

**Comment by jmazzitelli** [comment]
This passes on minikube but on OpenShift it fails now (given the current state of the server-side PR) - looks like it is due to a problem in server-side PR and its handling of Project vs.Namespace. But this molecule test should be good - and actually is doing its job detecting problems in the server. Once that problem is fixed, this test should all pass on OpenShift.

**Review by lucasponce — APPROVED** [review]

**Pull request merged**
