### PR TITLE
use new feature state=patched to better handle namespace labeling

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: kiali/kiali#3949

This requires PR https://github.com/kiali/kiali-operator/pull/460 to be merged first.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I ran this molecule test that passes - this would fail if the new "state: patched" option to the k8s task was not available. Because this passed, its clear we at least are picking up the latest ansible k8s collection with that new feature we've been waiting for.

`make -e CLUSTER_TYPE=minikube -e MOLECULE_USE_DEV_IMAGES="true" -e MOLECULE_SCENARIO="accessible-namespaces-test" molecule-test`

I have not tested the actual condition that QE found causes the initial failure. We need to confirm this actually fixes the problem.

**Review by jshaughn — DISMISSED** [review]
OK, there are some prerequisite PRs that need merging before this can be merged, but a visual inspection looks good to me.  The version updates look correct and the new option is in place.

**Comment by jmazzitelli** [comment]
after talking to @mattmahoneyrh and @jshaughn it has been decided that we will merge this PR and related PRs into master but will not backport anything. I will remove the DNM label

**Review by FilipB — APPROVED** [review]
Tried repro steps from https://github.com/kiali/kiali/issues/3949 with 20 namespaces and everything worked fine.

**Review by jshaughn — DISMISSED** [review]
Looks fine to me, visually.

**Comment by jmazzitelli** [comment]
@jshaughn @FilipB I need this re-approved. I actually added some commits to this PR and then realized those commits are unrelated to this "use new feature" issue. So I backed out those changed reverting this PR back to the way it was. But in doing all of this, I lost the approvals you put on this PR. So I need this re-approved.

**Review by FilipB — APPROVED** [review]

**Pull request merged**
