### PR TITLE
[v1.48] add back v1.12 ansible role

### PR DESCRIPTION
**Pull request by jmazzitelli**
This may not be needed, but there is talk it might be needed.

DO NOT MERGE this PR yet until a decision is made. If v1.12 role is needed in the v1.48 branch, we can merge this. If not, we can close this PR without merging.

### CODE REVIEW

**Comment by aljesusg** [comment]
We talked about it

https://github.com/kiali/kiali-operator/pull/496#pullrequestreview-909026024


Are we going to support 1.12 ?

**Comment by jmazzitelli** [comment]
> Are we going to support 1.12 ?

Some people want to re-visit that question. Since the question has come up again, I am just getting prepared in case we need to quickly bring back 1.12.

**Comment by jmazzitelli** [comment]
We are going to need to continue to support Kiali v1.12. This needs to be approved/merged.

**Review by aljesusg — APPROVED** [review]
LGFM we can merge it

**Comment by tsze-redhat** [comment]
This one reversed some of the changes from
https://github.com/kiali/kiali-operator/pull/496/files

**Pull request merged**
